import type { Grid } from "./api/types.svelte";

export const dummyGrid: Grid = {
  width: 15,
  height: 15,
  cells: [
    [
      {
        number: 1,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 2,
        value: {
          FilledChar: {
            value: "S",
            style: {
              colour: {
                red: 0,
                green: 255,
                blue: 255,
              },
              pattern: "HorizontalStripes",
            },
          },
        },
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 3,
        value: {
          FilledChar: {
            value: "S",
            style: {
              colour: {
                red: 0,
                green: 255,
                blue: 255,
              },
              pattern: "HorizontalStripes",
            },
          },
        },
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 4,
        value: {
          FilledChar: {
            value: "S",
            style: {
              colour: {
                red: 0,
                green: 255,
                blue: 255,
              },
              pattern: "HorizontalStripes",
            },
          },
        },
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 5,
        value: {
          FilledChar: {
            value: "S",
            style: {
              colour: {
                red: 0,
                green: 255,
                blue: 255,
              },
              pattern: "HorizontalStripes",
            },
          },
        },
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 6,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 7,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 8,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 9,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 10,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 11,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: "Space",
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 12,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 13,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 14,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 15,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 16,
        value: {
          FilledChar: {
            value: "D",
            style: {
              colour: {
                red: 0,
                green: 255,
                blue: 255,
              },
              pattern: "HorizontalStripes",
            },
          },
        },
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 17,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 18,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 19,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 20,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 21,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 22,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 23,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 24,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 25,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 26,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 27,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 28,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: "Hyphen",
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: "Space",
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 29,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: 30,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: 31,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
    [
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Closed",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
      {
        number: null,
        value: "Open",
        is_shaded: false,
        is_circle: false,
        across_word_end: null,
        down_word_end: null,
        has_right_bar: false,
        has_bottom_bar: false,
      },
    ],
  ],
};
